add a complex type de-serialization test
eldoriarpg/jackson-bukkit pull request #12
Opened 2023-03-17 15:23 UTC by yannicklamprecht

2023-03-17 17:47 UTC, yannicklamprecht commented on src/test/java/de/eldoria/jacksonbukkit/deserializer/ComplexPojoDeserializerTest.java
> +        var serverMock = spy(MockBukkit.mock());
spy can likely be removed here.

2023-03-17 17:47 UTC, yannicklamprecht commented on src/test/java/de/eldoria/jacksonbukkit/serializer/ComplexPojoSerializerTest.java
> +        var serverMock = spy(MockBukkit.mock());
py can likely be removed here.

2023-03-17 17:47 UTC, yannicklamprecht commented on src/test/java/de/eldoria/jacksonbukkit/templates/ComplexPojoTemplate.java
> +
reduce empty lines.

2023-03-17 22:09 UTC, rainbowdashlabs requested changes
Deletion of the empty files would be nice too uwu

2023-03-17 22:09 UTC, rainbowdashlabs commented on src/test/java/de/eldoria/jacksonbukkit/templates/ComplexPojoTemplate.java
> +            FireworkEffectTemplate.SINGLE,
Reformat?

2023-03-18 09:23 UTC, rainbowdashlabs approved these changes

2023-03-18 09:23 UTC, merged